### ISSUE TITLE
Fix for issue 5 broke sending for ademco/honeywell boards

### ISSUE THREAD

**Issue by jondthompson** [aficustree/homebridge-alarmdecoder-platform#10]
I tried manually removing the changes one at a time and it didn't fix it. I then reverted to 3.1.1 and it worked. Checking status works, but something breaks when sending codes.

Also, I suspect you can get which board it is from the status of the board rather than codifying it in the config. Mine sends "panel_type":"ADEMCO" on every status update.

**Comment by aficustree** [comment]
I think something in the DSC logic to try and fix the issues with DSC caused an issue when I merged it, I rebased it to 3.1.1 and updated to 3.1.5. can you try and let me know. Issue is I'm not at the house right now where we have the panel so I can't really test.

**Comment by jondthompson** [comment]
Yes, 3.1.5 works.
Jon Thompson
Evolve
515 360 1351
www.dmevolve.com
