### ISSUE TITLE
Homebridge alarmdecoder json format

### ISSUE THREAD

**Issue by fjublot** [aficustree/homebridge-alarmdecoder-platform#2]
Hello,
I want to use the homebridge-alarmdecoder plugin (the closed project). Can you send me a sample of the json response for the API that will send the alarm status? Thank you so much. Fred

**Comment by aficustree** [comment]
Hey, i haven’t looked at the old version in years. It was my first attempt at JavaScript and shows. Is there a reason you don’t want to use the platform version? It’s much better and pretty well tested. 

In any event, will try and help but not sure what you’re asking. Are you asking for the JSON response coming off the AlarmDecoder device? The folks that make that device have it published on [their site](http://www.alarmdecoder.com/swagger/index.html)

**Comment by fjublot** [comment]
thanks for you answer. I want to use your plugin in a special context. It's not for use with alarmdecoder but with another app witch expose also api. I will look at the alarmdecoder documentation and adapt the api of my specific app.
thank you so much
