### ISSUE TITLE
I'm missing something....

### ISSUE THREAD

**Issue by 7RDR7** [aficustree/homebridge-alarmdecoder-platform#20]
Please delete this error report. I went a different way and am no longer attempting to use this plugin.

**Comment by 7RDR7** [comment]
I've also tried HTTP and HTTPS on the above config, both fail. The AD2PI works fine with my Indigo plugin, but I want HomeKit support, hence trying to solve this challenge.

**Comment by jondthompson** [comment]
The user's issue was that he was pointing both the notification port and the API ports to the same port, which doesn't work.

Documentation should probably be better written to explain that the port: variable should be the same as what is set in https://alarmdecoder.local/settings/notifications/ , and that the URL variables should be the same as what is used on https://alarmdecoder.local/static/swagger/index.html

**Comment by aficustree** [comment]
accepted pull on clarifying docs
