### ISSUE TITLE
Npm and Git repos are out of sync

### ISSUE THREAD

**Issue by gdavids57** [aficustree/homebridge-alarmdecoder-platform#38]
When updating to the 3.1.8 release using the homebridge plugin admin facilities, I noticed my system did not contain the latest code.  Specifically, honeywell.js did not contain the changes associated with release 3.1.8.  Upon reviewing the code in the git repo and the npm repo and I find the code bases are not in sync.  It looks like the npm repo contains code from two years ago.  As I'm neither a git nor npm expert, what I'm observing may be perfectly normal, so take what I'm saying with a grain of salt.  Please note, if I manually issue, "npm install -g git+https://github.com/aficustree/homebridge-alarmdecoder-platform#master" from the linux command line, I get the correct code base.

**Comment by aficustree** [comment]
thanks for reporting, i published to npm

**Comment by gdavids57** [comment]
The repo's are still out of sync.  I think you can remedy the issue by updating the install command in the npm repo.  The command is currently, "npm i homebridge-alarmdecoder-platform" which pulls the old code.  I think you can update the install command to, "npm install -g git+https://github.com/aficustree/homebridge-alarmdecoder-platform#master" to fix the problem.  I'd do it myself but I don't have an npm account.

**Comment by aficustree** [comment]
i did a `npm publish` using the new version, it seems to be there. just tested by doing an npm install into a clean dir.

**Comment by aficustree** [comment]
ah nevermind, you're right. didn't see the error in my toolchain with all the github credential updates.

**Comment by aficustree** [comment]
should be fixed now

**Comment by gdavids57** [comment]
Works for me, as well.
