### ISSUE TITLE
A little confuse about the alarm-decoder web app.

### ISSUE THREAD

**Issue by ModMike** [aficustree/homebridge-alarmdecoder-platform#8]
Can this run on the Raspberry PI concurrently or it needs a standalone device?

Thanks!

**Comment by aficustree** [comment]
it's extremely lightweight, you can run it separately, on the some device you run the rest of homebridge, on the box that runs the alarmdecoder UI or whatever you have linked to the AD2USB.

**Comment by aficustree** [comment]
closing as no further question
